spring.application.name=connectify
server.port=8080

#Database Configuration
spring.datasource.url=${db_url}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Jpa/Hibernate Configuration
#Show SQL queries
spring.jpa.show-sql=true

#Auto DDL(Table create/update)
spring.jpa.hibernate.ddl-auto=update

#Formatting SQL queries
spring.jpa.properties.hibernate.format_sql=false

# Logging only for DEV profile
logging.level.root=INFO
logging.level.com.abubakar.connectify=DEBUG  

#image url
file.upload=./uploads/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB

#security config
#spring.security.user.name=abubakar
#spring.security.user.password=abubakar
#spring.security.user.roles=ADMIN

#Cache type
spring.cache.type=simple

#JWT TOKEN
#JWT(Access) Token ? 1 Day
#Refresh Token ? 30 Days
jwt_initial_secret_key=${jwt_initial_secret_key}
jwt_expiration=${jwt_expiration}
jwt_refresh_expiration=2592000000

# Swagger ui
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Frontend URL
app.frontend.url=http://localhost:5173

# TimeZone
spring.jackson.time-zone=UTC

# Lazy Loading
spring.jpa.open-in-view=false

#email configuration
spring.mail.host=${host}
spring.mail.port=${port}
spring.mail.username=${email_username}
spring.mail.password=${app_password}
spring.mail.properties.mail.smtp.auth=${smtp_auth}
spring.mail.properties.mail.smtp.starttls.enable=${smtp_starttls_enable}
spring.mail.properties.mail.smtp.starttls.required=${smtp_starttls_required}

# GOOGLE OAUTH2
spring.security.oauth2.client.registration.google.client-id=${google_client_id}
spring.security.oauth2.client.registration.google.client-secret=${google_client_secret}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# Github OAuth2
spring.security.oauth2.client.registration.github.client-id=${github_client_id}
spring.security.oauth2.client.registration.github.client-secret=${github_client_secret}
spring.security.oauth2.client.registration.github.scope=user:email
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
