package com.abubakar.connectify.enums;

public enum NotificationType {

    LIKE,
    COMMENT,
    FOLLOW,
    REPLY,
    STORY_REACTION,
    STORY_REPLY,
    POST_REMOVED,
    ACCOUNT_BANNED,
    ACCOUNT_UNBANNED,
    ACCOUNT_RESTORED,
    UNBAN_APPROVED,
    UNBAN_REJECTED,
    ACCOUNT_DELETED,
    MESSAGE,
    CHAT_DELETED_BY_ADMIN,
    MESSAGE_DELETED_BY_ADMIN,
    RESTORE_REQUEST,
    RESTORE_REQUEST_REJECTED,
    POST_RESTORED,
    POST_RESTORE_REJECTED,
    POST_REPORTED,
    COMMENT_REPORTED,
    USER_REPORTED,
    MESSAGE_REPORTED,
    STORY_REPORTED,
    CHAT_REPORTED

}

