package com.abubakar.connectify.enums;

public enum NotificationType {

    LIKE,
    COMMENT,
    FOLLOW,
    REPLY,
    CHAT,
    STORY_REACTION,
    STORY_REPLY,

    POST_REMOVED,
    POST_RESTORED,
    POST_RESTORE_REJECTED,

    STORY_REMOVED,
    STORY_RESTORED,
    STORY_RESTORE_REJECTED,

    ACCOUNT_BANNED,
    ACCOUNT_RESTORED,
    UNBAN_APPROVED,
    UNBAN_REJECTED,
    ACCOUNT_DELETED,

    MESSAGE,
    CHAT_DELETED_BY_ADMIN,
    MESSAGE_DELETED_BY_ADMIN,

    CHAT_RESTORED,
    CHAT_RESTORE_REJECTED,

    MESSAGE_RESTORED,
    MESSAGE_RESTORE_REJECTED,

    RESTORE_REQUEST,
    RESTORE_REQUEST_REJECTED,

    POST_REPORTED,
    COMMENT_REPORTED,
    USER_REPORTED,
    MESSAGE_REPORTED,
    STORY_REPORTED,
    CHAT_REPORTED
}

